# CONFIGURATION PARAMETERS OF USB CONNECTION #
USB_port=/dev/ttyUSB*
# CHOOSE ANOTHER BAUDRATE BASED ON THE BOARD #
BAUDRATE=115200
# ERRORS AND CHECK OF USB CONNECTION #
ERROR_CONNECTION=2
ERROR_COMUNNICATION=1
RETURN_RESET_OK=0
